Fix/UI hang on stop#17
ajayd-san/gomanagedocker pull request #20
Opened 2024-07-18 11:23 UTC by ashishkhuraishy

fixes #17

2024-07-18 17:37 UTC, ajayd-san commented
Hey, great job on the PR!

Can you make `handleBackground` a `MainModel` method ? Everything else would be the same. We can use this method to port existing blocking operations in the next release.

Thanks

2024-07-19 05:16 UTC, ashishkhuraishy commented
added it as part of the MainModel and refactored a couple of blocking functions

2024-07-19 15:15 UTC, ajayd-san requested changes
Hey, pl make the suggested changes. Thanks!

2024-07-19 15:15 UTC, ajayd-san commented on tui/mainModel.go
> +
We should consider making this a pure function. 

i.e pass in `id` to the function as well. Cuz we cannot determine when a go routine will be scheduled to run. If the user somehow is selecting a different list item when `handleBackground` gets run, the `operation` will be run on that item instead. Which is not supposed to happen.
 
```suggestion
func (m MainModel) handleBackground(operation func(string) error, id string) {
	m.possibleLongRunningOpErrorChan <- operation(id)
}

```

2024-07-19 15:15 UTC, ajayd-san commented on tui/types.go
these changes are unrelated to this issue. I've already merged your PR #19  that has these changes.

2024-07-19 15:15 UTC, ajayd-san commented on tui/mainModel.go
> +					go m.handleBackground(m.dockerClient.ToggleStartStopContainer)
and update these to get current Id and abide by the newly suggested function signature for `m.handleBackground`.

2024-07-22 02:21 UTC, ajayd-san commented
Hey @ashishkhuraishy , If you are still working on this. I'd recommend you rebase against `notification_system`.

2024-08-20 15:55 UTC, closed without merging